### ISSUE TITLE
Use zprint 1.2.7 

### ISSUE THREAD

**Issue by amithgeorge** [rflagreca/vscode-clj-zprint#10]
Version 1.2.7 has been out for a few months now. Does the extension need to be upgraded to support it? Or can we provide a path to our local zprint jar? We use deps.edn dependency to run zprint.

**Comment by rflagreca** [comment]
Hey @amithgeorge - yes, the extension needs to be updated to support any new version release.  I'll try to get round to it this weekend.  Thanks!

**Comment by rflagreca** [comment]
Hey @amithgeorge - sorry for the delay.  I've updated the extension to v0.0.8 which uses zprint v1.2.7.
