### ISSUE TITLE
VSCode configuration of zprint

### ISSUE THREAD

**Issue by kkinnear** [rflagreca/vscode-clj-zprint#4]
First, thanks for taking the pull request! That is very generous of you! I had no idea this was your first OSS venture.  You put together a totally functional extension that it was a pleasure to extend.  

I'm (perhaps belatedly) sensitive to my possibly being over-enthusiastic with my contributions to this extension.  Am I getting in the way of things you want to do but just haven't gotten around to yet?   I have had that happen to me, and I really didn't appreciate it.  I bring this up in part because there is one more thing that I was hoping to contribute to your extension before I moved on to other activities.  If you would rather I didn't create a pull request with some of these things, below, I would be disappointed but I would certainly understand.  So, please let me know.

My thoughts for "one more thing"...

Before I return to adding some new features to zprint, there is one more feature I thought might be useful for this extension.  It seems like many extensions have some configurable elements that can be changed in VSCode directly.  Seemed like maybe a good idea for this extension too. I was playing around with some of these things, and I seem to have figured out how to build commands and configuration elements for extensions in VSCode.  The things that it seemed like it might be nice to be able to do directly in VSCode (instead of, maybe, editing `.zprintrc` configuration files) are:

Commands:
- Some command to cause the extension to re-read the `.zprintrc` (or `.zprint.edn`) configuration files, in case you have changed them.  This way you don't have to exit vscode to get it to look again at the configuration files.
- Some command to output the current non-default configuration items in zprint to the output channel, so you can see what configuration you are currently using (and where the non-default values came from).  I needed this for debugging the next bit, but it seems in retrospect like a useful thing in its own right.

Configuration
- The `:width` would be nice to set directly, and not have to mess with the config files.
- The `:style` seemed to me to be an obvious thing to want to change in VSCode directly.  In thinking about it, it seemed like there were two different approaches to styles that might be useful:

1. Additional styles: where the styles you configure would be added on to whatever was in the config files.
2. Use only these styles: where the styles configured would be only styles used.

I have code that pretty much does those things above, though it needs to be cleaned up a good bit.   It was an interesting experience playing with vscode commands and configuration.  I certainly learned a lot.  While testing the style stuff, I found that Zprint's style configuration was broken for complex styles, so I've spent the last few days pretty much rewriting how zprint handles style configuration.  I have a few more days to finish that up and release yet another version of zprint in the next week or so.

If you are ok with this additional contribution, there are several questions where I could use your input:

1. The name which goes at the top of the configuration section.  This is also the name which goes in the list which shows up under "Settings" , "Extensions".  It could be `vscode-clj-zprint`, but other extensions don't seem to use their full extension name for the things that shows up in this list.  So "VSCode Neovim" becomes "Neovim", and likewise for other stuff.  I was thinking perhaps just `zprint`, though every other thing is capitalized, so perhaps `Zprint` might be the best?  Coming last isn't necessarily a bad thing, as then you can just scroll quickly to the bottom.   Other ideas?

2. Naming the commands.  At present I have two commands, one named `zprint refresh configuration` and one named `zprint output current configuration`.   Looking at other commands, these don't quite fit in.  They could maybe be `Zprint: Refresh Configuration` and `Zprint: Output Current Configuration` and that might fit in better with other commands, many of which have something with a colon on the front and are capitalized.  But there might be some other way to name them that I haven't thought about.  As a vscode user you probably know a lot more about what "fits in" than I do.

3. And of course, what other configuration things would be nice to be able to change.  zprint is way too configurable, but the things that people actually change seem to be the styles, the width, and maybe the `:fn-map`.  I suppose there might be a useful way to allow people to augment the `:fn-map` from vscode.  What do you change in zprint?  I don't change anything, I built it the way I like to use it. 

4. I suppose one additional thing might be a Boolean for community standard formatting.  That is apparently what the built-in Calva formatter does, and while I'm personally not a fan of the "community" formatting standard (as a Lisp programmer from way back), I guess a lot of people think that is the way to go.  Instead of making people select that as a style, it could just be a boolean to turn on if you want it.  It would be a little tricky getting that into the styles correctly, but I think I could make that work.  Would that be useful?

5.  Are there other things?

Let me know what you think.  And thank you for welcoming my any of my contributions, it is very generous of you.

As soon as I'm through with whatever else I'm going to contribute to this extension( if anything),  I'm going to probably re-write the way zprint does range formatting.  Turns out that if you use the comment API, where you put `;!zprint {<options-map}` in the source, that the range formatting will only pick up the comment that is immediately before the range you selected.  This hasn't bothered me much up until now, as I haven't really used the range formatting myself.  I don't even know if the guy that requested it ever used it, as it took me months to build it and get it to work.  But with the range formatting being used all the time with this extension, the fact that it doesn't really interpret all of the zprint comment API option maps prior to the range is slightly annoying, as I do use the comment API myself a bit to tweak how this or that thing is formatted.  I think I have a way to get zprint to figure out how to use all of the previous comment API things when doing a range, but I need to see if I can make it work.   That will be a good for a few weeks work.

**Comment by rflagreca** [comment]
Hi @kkinnear - sorry for the late reply, I've been very busy over the last weeks.

> I'm (perhaps belatedly) sensitive to my possibly being over-enthusiastic with my contributions to this extension. Am I getting in the way of things you want to do but just haven't gotten around to yet? I have had that happen to me, and I really didn't appreciate it. I bring this up in part because there is one more thing that I was hoping to contribute to your extension before I moved on to other activities. If you would rather I didn't create a pull request with some of these things, below, I would be disappointed but I would certainly understand. So, please let me know.

You're absolutely not getting in the way - I'm very grateful for the contributions.  I've very limited time to work on the project at the moment and it was fulfilling my needs as it was, so to have others step in and contribute extra functionality that has been requested is really helpful.

> Before I return to adding some new features to zprint, there is one more feature I thought might be useful for this extension. It seems like many extensions have some configurable elements that can be changed in VSCode directly. Seemed like maybe a good idea for this extension too. I was playing around with some of these things, and I seem to have figured out how to build commands and configuration elements for extensions in VSCode.

I had actually thought that this would be a nice feature to add at some point when I was first developing the extension so I am all for you adding commands and configuration for zprint directly in vscode!

I'll try to answer the questions you've posed now the best I can.

1. I think we should stick to the convention that seems to have been adopted by other extensions - so, capitalised `Zprint`
2. Again, I think we should stick with convention here, so command name should be like `Zprint: Refresh Configuration` and `Zprint: Output Current Configuration`
3. I'm like you - I rarely change configuration so it may be better to survey other users of `zprint` to see which other configuration options they would like to change.
4. I think this could be a useful one, although I probably wouldn't use it, I can imagine others having a use for this - (perhaps when they are contribution to other projects that they don't own, etc)
5. Nothing else that I can think of.

Thanks again for your contributions!   Looking forward to seeing what you've come up with in this area!

**Comment by kkinnear** [comment]
I'm sure glad you responded as you did, as I have continued to work on it and I would hate to throw all that work away!  Thanks!

I have actually largely finished (just today, interestingly enough), the extension work.  I will fold in changes from your comments, above.  I have not yet released a new version of zprint with the fixes to the style configuration, though I did them a week or two ago.  I think the vscode local configuration of the extension would not be great without the fixes to the style configuration in zprint, so I will release a new version of zprint, and then generate the pull request for the extension.  

I'll have more to say in the pull request itself, but it was interesting to see that the error handling for the vscode local configuration and how that interacted with the configuration from the command files was about as much work as the rest of the local vscode configuration.  Anyway, it will be a day or two before I can finish up the zprint release, but you should see a pull request pretty soon.

Again, thanks for welcoming contributions!
