### ISSUE TITLE
Request: Either update the zprint version or allow pointing to a binary in config

### ISSUE THREAD

**Issue by riotrah** [rflagreca/vscode-clj-zprint#6]
Hello!

Thanks for this. It works beautifully.

Unfortunately, and understandably, it hasn't yet been updated to the [latest version, which includes a feature I had requested](https://github.com/kkinnear/zprint/issues/239#issuecomment-1202980786). 

1. A "quick fix", depending on how your extension acquires or loads zprint, would be to simply update that version and push a new version of the extension.

2. A "longer term fix" perhaps, if it's feasible, is to allow users to point to arbitrary zprint binaries somehow in vscode config, that way you're not always on the hook for updating zprint yourself for/within the extension.

I haven't looked at the source yet, so forgive the armchair suggestions if they're dumb.

Anyways, thanks again for this!

**Comment by rflagreca** [comment]
Hi @riotrah - sorry for the late reply and thank you for raising this issue!

Ideally I would like to proceed with your "longer term fix" suggestion and allow users to provide their own zprint binary.  Like yourself, I'm not sure on the feasibility of this, so would require a bit of investigation and work and I'm not sure when I would be able to get to this.  Please feel free to have a dig yourself and open a PR if you come up with an acceptable solution :)

In the meantime, I will bump the version used internally to the latest zprint version.  I will try to get this done by the weekend.

Thanks again.

**Comment by rflagreca** [comment]
@riotrah - I've updated the extension to v0.0.5 which packages zprint 1.2.4.  I'll leave this issue open as I'd like to implement the solution where users can specify their own zprint binary.

**Comment by riotrah** [comment]
Thanks, appreciate that - lemme know if you'd life help with that

**Comment by rflagreca** [comment]
Hi @riotrah

See https://github.com/rflagreca/vscode-clj-zprint/issues/8

I've had to roll back the bundled zprint version to 1.2.2 and need to do some more work to get versions >= 1.2.3 compatible with the extension.  I'll write up a full explainer of the issue with newer versions soon and create a new issue.  Sorry for any inconvenience.

**Comment by riotrah** [comment]
I see you'veupdated to `1.2.4` - I take it the above concerns are resolved? If so, shall we close this? 

(I still notice that `max-gap` - a 1.2.4 feature - throws an error in the extension, but this might be some other error or issue)

**Comment by riotrah** [comment]
hi @rflagreca,

No need to apologize, I'm certainly not entitled to your free time haha.

However, there's quite a few features that I've wanted to use from recent versions of `zprint`. So in light of that, **I'd like to help as much as possible**, and would love if you could give me pointers as to where to start. I'm quite comfortable with vsc extension API.

If you could:

1. Please explain even in little detail how different versions of `zprint` affect this extension (ie why it would crash from the linked issue)

3. Please advise if you have any suggestions, worries or insight into my original suggestions above:
   A. Implementing a configurable path to a `zprint` binary, either instead of, or alternative to a builtin version.
      - I imagine you're familiar, but that's what `calva` does for `clojure-lsp`, for example
   B. Otherwise at least simply upgrading to the latest version of `zprint`

**Comment by rflagreca** [comment]
Hi @riotrah - see PR #9 where I've fixed the issue with newer zprint versions.

There was a change to `zprint.config/config-configure-all!` where it required the config to be locked before calling, or else it would throw an error.

Regarding providing a custom zprint binary - currently we use the shadow-cljs package manager to manage the zprint dependency which pulls the required version when the extension is packaged.  We call the packaged zprint's functions directly from core.cljs and hook them up to vscodes formatter functions.
  
I haven't scoped it, but supporting the binary version would likely require a fairly large refactor and wouldn't be as well featured.

Please feel free to explore adding support for a custom zprint binary and I'd be happy to review and consider any additions, however I won't be actively adding new features to this extension myself.  
I will however keep an eye on updates to zprint upstream and release new versions of this extension including them when I can (providing they don't break the extension again!)
